server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: borrow
          uri: http://localhost:8081/
          predicates:
            - Path=/api/**

        - id: book
          uri: http://localhost:8082/
          predicates:
            - Path=/bibli/**
        - id: student
          uri: http://localhost:8084/
          predicates:
            - Path=/bibl/**






